#include "my_uart.h"

#if 1	/* UART0 console (base feature). */

/*
 * Initialize UART0 as an 8-bit asynchronous port clocked by the dedicated
 * BRT baud rate timer:
 *   - Baud rate: MY_UART_BAUD_RATE, using the precomputed MY_UART_BRT_PERIOD
 *     unless USE_FORMULA is defined, in which case the driver derives it.
 *   - Pins: MY_UART_TX_PIN / MY_UART_RX_PIN muxed to TXD0 / RXD0.
 *   - Receive interrupt enabled; received bytes are echoed back by
 *     UART0_IRQHandler_Task().
 */
void UART0_Config(void)
{
	uint16_t BRTValue = 0;

	/* 8-bit asynchronous mode, baud rate generated by the BRT timer. */
	UART_ConfigRunMode(UART0, UART_MOD_ASY_8BIT, UART_BAUD_BRT);
	UART_EnableReceive(UART0);

	/* BRT clock = Fsys / 1, and enable the baud rate doubler (SMOD = 1). */
	UART_ConfigBRTClk(BRT_CLK_DIV_1);
	UART_EnableDoubleFrequency(UART0);

#ifdef USE_FORMULA
	/* Let the driver derive the reload value from Systemclock. */
	BRTValue = UART_ConfigBaudRate(UART0, MY_UART_BAUD_RATE);
#else
	/* Precomputed value for the 48 MHz / 9600 bps configuration. */
	BRTValue = MY_UART_BRT_PERIOD;
#endif

	/* Load BRTH:BRTL and start the baud rate timer. */
	UART_ConfigBRTPeriod(BRTValue);
	UART_EnableBRT();

	/* Route the UART0 signals to the selected port pins. */
	GPIO_SET_MUX_MODE(MY_UART_TX_PIN, GPIO_MUX_TXD0);
	GPIO_SET_MUX_MODE(MY_UART_RX_PIN, GPIO_MUX_RXD0);

	/* Enable the UART interrupt at the lowest priority level. */
	UART_EnableInt(UART0);
	IRQ_SET_PRIORITY(IRQ_UART0, IRQ_PRIORITY_LOW);
	IRQ_ALL_ENABLE();
}

/*
 * UART0 interrupt task. Must be called from the UART0 ISR (see isr.c).
 * Clears the transmit flag and echoes every received byte back to the host.
 */
void UART0_IRQHandler_Task(void)
{
	if(UART_GetSendIntFlag(UART0))
	{
		UART_ClearSendIntFlag(UART0);
	}
	if(UART_GetReceiveIntFlag(UART0))
	{
		/* Echo: send back the byte that was just received. */
		UART_SendBuff(UART0, UART_GetBuff(UART0));
		UART_ClearReceiveIntFlag(UART0);
	}
}

/*
 * Low-level character output used by the C51 library (printf -> putchar).
 * Polls TI0 instead of using interrupts; UART0 interrupts are temporarily
 * disabled so the ISR and this function never write SBUF0 at the same time.
 */
char putchar(char ch)
{
	uint8_t uart0_int_enabled = ES0;

	ES0 = 0;
	SCON0 &= ~(UART_SCON0_TI0_Msk);	/* Clear TI0 before sending. */
	SBUF0 = ch;
	while(!(SCON0 & UART_SCON0_TI0_Msk))	/* Wait until TI0 is set. */
	{
		;
	}
	SCON0 &= ~(UART_SCON0_TI0_Msk);	/* Clear TI0 for the next byte. */
	ES0 = uart0_int_enabled;

	return ch;
}

/*
 * Low-level character input: blocks until a byte is received, then returns
 * it. Interrupts are masked for the same reason as in putchar().
 */
char getchar(void)
{
	uint8_t uart0_int_enabled = ES0;
	char ch;

	ES0 = 0;
	while(!(SCON0 & UART_SCON0_RI0_Msk))	/* Wait until RI0 is set. */
	{
		;
	}
	ch = SBUF0;
	SCON0 &= ~(UART_SCON0_RI0_Msk);	/* Clear RI0 to allow the next byte. */
	ES0 = uart0_int_enabled;

	return ch;
}

/* Minimal string output helper built on putchar(). */
int puts(const char *s)
{
	while(*s)
	{
		putchar(*s++);
	}

	return 0;
}

#endif	/* UART0 console */


